- backend/controllers/feed-controllers.go
- backend/go.mod
- backend/go.sum
- backend/main.go
- backend/models/Comment.go
- backend/models/Likes.go
- backend/models/UserPost.go
- backend/utils/db_setup.go
@SnehaParuchuri Modified feed retrieval service to retrieve posts along with comments. The posts are retrieved in descending order of time created. Comments are also sorted by time in descending order
> Modified feed retrieval service to fetch comments along with posts

- backend/controllers/feed-controllers.go
- sprint1.md
@VishnuJammula , please check it now
> changed spell

- backend/controllers/UserProfileController.go
- backend/controllers/UserProfileController_test.go
- backend/main.go
- backend/models/User.go
- backend/utils/db_setup.go
Test out user bio updation before merging
> User profile updation

- backend/controllers/UserProfileController_test.go
- backend/utils/mock-db_setup.go
@SnehaParuchuri Please review and merge PR for unit tests of user profile services
> User profile unit tests

- .gitignore
- backend/controllers/UserProfileController.go
- backend/go.mod
- backend/go.sum
- backend/main.go
- backend/models/User.go
This PR has changes for resume upload service. @SnehaParuchuri Please review and accept
> #96: resume upload service

- frontend/src/dashboard/LoginPage/LoginForm.js
- frontend/src/dashboard/Settings/MyProfile/MyProfile.js
- frontend/src/dashboard/Settings/Settings.css
input fields are no longer shrinking.
> Closes the issue #94

- backend/controllers/UserProfileController_test.go
- backend/controllers/jobposts-controller.go
- backend/controllers/jobposts-controller_test.go
- backend/main.go
- backend/models/JobApplication.go
- backend/models/JobPost.go
This PR has job retrieval apis and model changes for Job Posts
> Job retrieval api

- backend/controllers/jobposts-controller.go
- backend/main.go
- backend/models/JobPost.go
> Backend myapplications

- backend/controllers/jobposts-controller.go
- backend/models/JobPost.go
@SnehaParuchuri please review and approve this. This PR has api for retrieving a list of job applications for a job posting
> #95 job applications retrieve service

- backend/controllers/jobposts-controller.go
- backend/controllers/jobposts-controller_test.go
@SnehaParuchuri This PR has fix for #114 and related unit tests
> Backend unit tests

- frontend/src/dashboard/Settings/MyProfile/MyProfile.js
- frontend/src/dashboard/Settings/Settings.css
> Jobsposted

- frontend/src/dashboard/Settings/MyProfile/MyProfile.js
- frontend/src/dashboard/Settings/Settings.css
- frontend/src/dashboard/Settings/Settings.test.js
> Posted apps

- frontend/src/dashboard/Jobs/Jobs.js
- frontend/src/dashboard/Jobs/PostedJobs/ApplicantCard.css
- frontend/src/dashboard/Jobs/PostedJobs/ApplicantCard.js
- frontend/src/dashboard/Jobs/PostedJobs/Applicants.css
- frontend/src/dashboard/Jobs/PostedJobs/Applicants.js
- frontend/src/dashboard/Jobs/PostedJobs/PJCard.css
- frontend/src/dashboard/Jobs/PostedJobs/PJCard.js
- frontend/src/dashboard/Jobs/PostedJobs/PostJob.css
- frontend/src/dashboard/Jobs/PostedJobs/PostJob.js
- frontend/src/dashboard/Jobs/PostedJobs/PostedJobs.css
- frontend/src/dashboard/Jobs/PostedJobs/PostedJobs.js
Completed Employer Dashboard.
Please review! @flash29
> #133 completed

- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/NavBar/NavBar.js
- frontend/src/components/Popup.css
- frontend/src/components/Popup.js
- frontend/src/components/PostBox/PostBox.css
- frontend/src/components/PostBox/PostBox.js
- frontend/src/dashboard/Jobs/MyApps/MyApps.js
- frontend/src/dashboard/Jobs/PostedJobs/PostJob.css
- frontend/src/dashboard/Jobs/PostedJobs/PostedJobs.css
- frontend/src/dashboard/Jobs/PostedJobs/PostedJobs.js
- frontend/src/dashboard/LoginPage/LoginForm.js
- frontend/src/dashboard/Registration/RegForm.js
Fixed all the mentioned bugs in login and postbox. Please review! @flash29
> 134 login and postbox bugs

- backend/controllers/connections-controller.go
- backend/controllers/jobposts-controller.go
- backend/controllers/logout-controller.go
- backend/main.go
- backend/models/ConnectionRequest.go
- backend/models/JobApplication.go
- backend/utils/mock-db_setup.go
Added **userName** in job application structure and added it to database in **ApplyToJob** function.
@VishnuJammula @vangmayi98  please review.
> 150 attribute addition to applieduserslist

- backend/controllers/connections-controller.go
- backend/controllers/logout-controller.go
- backend/main.go
- backend/models/ConnectionRequest.go
- backend/utils/mock-db_setup.go
Added a new method to retrieve connections that are requested. Added a new field **requestorName** in the structure to display in UI. Changed numeric status codes to http ones. Added userToken in mock database connection.
@VishnuJammula please review.
> fixes #140 retrieve conenction requests

- frontend/src/dashboard/Jobs/JobSearch/JobSearch.js
- frontend/src/dashboard/Jobs/Jobs.js
- frontend/src/dashboard/Jobs/PostedJobs/ApplicantCard.js
- frontend/src/dashboard/Jobs/PostedJobs/Applicants.js
> #154 resolved

- backend/controllers/search-controller.go
- backend/main.go
- backend/middleware/middleware.go
@SnehaParuchuri this PR has code changes for people search api. The query param given is searched against user's email, name and bio
> #142: api for people search by mail, name, bio

- frontend/src/App.js
- frontend/src/auth/ProtectedRoute.js
User now cant access routes that he is not allowed to.
When user is not logged in he cant access the home page and other dashboards.
> Added Protected Route

- backend/controllers/connections-controller.go
- backend/main.go
Added a new method to get the people who have same edu inst. or company as the user. If the user did not add edu or job details a maximum of 10 users who are not connected to the current user will be returned.
@VishnuJammula please review.
> fixes #139 people you may know

- backend/controllers/connections-controller.go
- backend/main.go
Added a new method to retrieve username and id for followers. UI needed to display the followers user name and id is used to open the profile page.
@VishnuJammula please review
> fixes #160 , UI needs to display name as well

- backend/controllers/search-controller.go
- backend/main.go
@SnehaParuchuri This PR is for Job search API. Review and Approve
> #143: jobs search api

- backend/controllers/connections-controller.go
- backend/main.go
added a new function to decline a connection request. @VishnuJammula please review.
> fixes #158 decline a request

- backend/controllers/feed-controller.go
- backend/main.go
- backend/models/UserPost.go
@SnehaParuchuri This PR has changes to fetch the feed posts from following id's. Also made creator user_id mandatory for feed post creation. Review and approve.
> Feed posts

- backend/controllers/connections-controller.go
Added "distinct" to query and updated paranthesis in  "or, and" conditions in query.
> fixes #170

- backend/controllers/login-controller.go
- backend/utils/login-util.go
- backend/utils/login-util_test.go
@SnehaParuchuri Returning username in login response. Please review and approve.
@vangmayi98
> #173: included user name in login response

- backend/controllers/connections-controller_test.go
Added testcases for connections controller.
@VishnuJammula please review.
> added testcases related to connections

- backend/controllers/feed-controller.go
- backend/controllers/feed-controller_test.go
- backend/controllers/logout_test.go
- backend/controllers/search-controller_test.go
@SnehaParuchuri . This PR has changes for unit tests for Logout, Updated Feed posts & Search API's
> Search api unit tests

- frontend/package-lock.json
- frontend/package.json
- frontend/src/dashboard/Search/Search.js
- frontend/src/dashboard/Search/Search.test.js
Written unit tests for Search. Please review @flash29
> 184 unit tests for search
